pipeline {
    agent any

    stages {

        stage('Clone') {
            steps {
                git 'https://github.com/vishal030308-star/3tire.git'
            }
        }

        stage('Build') {
            steps {
                sh 'docker-compose build'
            }
        }

        stage('Deploy') {
            steps {
                sh 'docker-compose up -d'
            }
        }
    }
}